# Generated by Django 5.1.1 on 2025-01-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='tin_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
