# Generated by Django 5.1.1 on 2024-11-05 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(default=1992, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.order'),
        ),
    ]
